#!/usr/bin/env bash

prefix="vcw_module_vcwc_streamsets_traefik__$1"
prefix="vcw_module_vcwc_streamsets_traefik__$1"

executionplane --silent docker container prune --force

if [[ "vcw_module_vcwc_streamsets_traefik__streamsets_streamsets_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_vcwc_streamsets_traefik__streamsets_streamsets_volume"
		result=$(docker volume ls | grep "vcw_module_vcwc_streamsets_traefik__streamsets_streamsets_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
