#!/usr/bin/env bash

prefix="vcw_module_vcwc_streamsets_traefik__$1"
prefix="vcw_module_vcwc_streamsets_traefik__$1"

if [[ "vcw_module_vcwc_streamsets_traefik__streamsets_streamsets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_vcwc_streamsets_traefik__streamsets_streamsets_volume
fi

if [[ "vcw_module_vcwc_streamsets_traefik__streamsets_streamsets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcw_module_vcwc_streamsets_traefik__streamsets_streamsets_volume:/data ${VCW_REGISTRY}vcwc/controlplane.vcw console untar /source/vcwc/streamsets/traefik/_module/volumes/streamsets_streamsets_volume.tar
fi
