#!/usr/bin/env bash

prefix="vcwc_streamsets_traefik__$1"
prefix="vcwc_streamsets_traefik__$1"

executionplane --silent docker container prune --force

if [[ "vcwc_streamsets_traefik__streamsets_streamsets_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_streamsets_traefik__streamsets_streamsets_volume"
		result=$(docker volume ls | grep "vcwc_streamsets_traefik__streamsets_streamsets_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcwc_streamsets_traefik__streamsets_nginx_config_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_streamsets_traefik__streamsets_nginx_config_volume"
		result=$(docker volume ls | grep "vcwc_streamsets_traefik__streamsets_nginx_config_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
